/*
Support for request body and parameter examples

Testing MultipleMediaTypesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package requestexample

import (
	"context"
	"testing"

	openapiclient "github.com/ibiscum/go-oas-examples"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_requestexample_MultipleMediaTypesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test MultipleMediaTypesAPIService PostRequestBodyMultiMediaTypes", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.MultipleMediaTypesAPI.PostRequestBodyMultiMediaTypes(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
