/*
Support for request body and parameter examples

Testing SingleExampleAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package requestexample

import (
	"context"
	"testing"

	openapiclient "github.com/ibiscum/go-oas-examples"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_requestexample_SingleExampleAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test SingleExampleAPIService PostRequestBodyPrimitiveExample", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.SingleExampleAPI.PostRequestBodyPrimitiveExample(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SingleExampleAPIService PutParameterExamplesParam1Param2", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		var param1 string
		var param2 string

		resp, httpRes, err := apiClient.SingleExampleAPI.PutParameterExamplesParam1Param2(context.Background(), param1, param2).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SingleExampleAPIService RequestBodyPatch", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.SingleExampleAPI.RequestBodyPatch(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test SingleExampleAPIService RequestBodyPut", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		resp, httpRes, err := apiClient.SingleExampleAPI.RequestBodyPut(context.Background()).Execute()

		require.Nil(t, err)
		require.NotNil(t, resp)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
