swagger: '2.0'
tags:
  - name: operation
info:
  contact:
    name: Example
  title: Circular reference examples
  description: Description of circular reference examples
  version: '1.0'
schemes:
  - http
host: httpbin.org
paths:
  '/post':
    post:
      operationId: post-post
      description: Description of operation post-post
      tags:
        - operation
      parameters:
        - in: body
          name: body
          schema:
            '$ref': '#/definitions/node'
      responses:
        '200':
          description: Circular
definitions:
  node:
    type: object
    properties:
      children:
        type: array
        items:
          '$ref': '#/definitions/node'
