/*
HTTP Status Codes

Testing ServerErrorResponsesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package httpstatus

import (
	"context"
	"testing"

	openapiclient "github.com/ibiscum/go-oas-examples/3.0/yaml/http-status-codes/httpstatus"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_httpstatus_ServerErrorResponsesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test ServerErrorResponsesAPIService GetStatus500", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.ServerErrorResponsesAPI.GetStatus500(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ServerErrorResponsesAPIService GetStatus501", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.ServerErrorResponsesAPI.GetStatus501(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ServerErrorResponsesAPIService GetStatus502", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.ServerErrorResponsesAPI.GetStatus502(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ServerErrorResponsesAPIService GetStatus503", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.ServerErrorResponsesAPI.GetStatus503(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ServerErrorResponsesAPIService GetStatus504", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.ServerErrorResponsesAPI.GetStatus504(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ServerErrorResponsesAPIService GetStatus505", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.ServerErrorResponsesAPI.GetStatus505(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ServerErrorResponsesAPIService GetStatus506", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.ServerErrorResponsesAPI.GetStatus506(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ServerErrorResponsesAPIService GetStatus507", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.ServerErrorResponsesAPI.GetStatus507(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ServerErrorResponsesAPIService GetStatus508", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.ServerErrorResponsesAPI.GetStatus508(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ServerErrorResponsesAPIService GetStatus509", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.ServerErrorResponsesAPI.GetStatus509(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ServerErrorResponsesAPIService GetStatus510", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.ServerErrorResponsesAPI.GetStatus510(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ServerErrorResponsesAPIService GetStatus511", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.ServerErrorResponsesAPI.GetStatus511(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ServerErrorResponsesAPIService GetStatus512", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.ServerErrorResponsesAPI.GetStatus512(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ServerErrorResponsesAPIService GetStatus520", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.ServerErrorResponsesAPI.GetStatus520(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ServerErrorResponsesAPIService GetStatus522", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.ServerErrorResponsesAPI.GetStatus522(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ServerErrorResponsesAPIService GetStatus523", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.ServerErrorResponsesAPI.GetStatus523(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ServerErrorResponsesAPIService GetStatus524", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.ServerErrorResponsesAPI.GetStatus524(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ServerErrorResponsesAPIService GetStatus525", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.ServerErrorResponsesAPI.GetStatus525(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ServerErrorResponsesAPIService GetStatus526", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.ServerErrorResponsesAPI.GetStatus526(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ServerErrorResponsesAPIService GetStatus527", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.ServerErrorResponsesAPI.GetStatus527(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ServerErrorResponsesAPIService GetStatus529", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.ServerErrorResponsesAPI.GetStatus529(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ServerErrorResponsesAPIService GetStatus530", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.ServerErrorResponsesAPI.GetStatus530(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test ServerErrorResponsesAPIService GetStatus598", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.ServerErrorResponsesAPI.GetStatus598(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
