openapi: 3.0.0
tags:
  - name: pet
info:
  contact:
    name: API Support
    url: http://www.example.com/support
    email: support@example.com
  version: 1.0.0
  title: Simple Petstore
  description: This is a slimmed down single path version of the Petstore definition.
servers:
  - url: https://httpbin.org
paths:
  '/pet/{id}':
    parameters:
      - name: id
        description: Identifier for pet
        in: path
        required: true
        schema:
          example: 123
          type: integer
    put:
      operationId: put_pet
      tags:
        - pet
      summary: Update a pet
      description: This operation will update a pet in the database.
      responses:
        '200':
          description: Ok
        '400':
          description: Invalid id value
      security:
        - apiKey: []
    get:
      operationId: get_pet
      tags:
        - pet
      summary: Find a pet
      description: This operation will find a pet in the database.
      responses:
        '200':
          description: Finding a pet was successful
        '400':
          description: Invalid status value
      security: []
components:
  securitySchemes:
    apiKey:
      description: Security scheme
      type: http
      scheme: basic
