openapi: 3.0.3
tags:
  - name: additional
info:
  contact:
    name: Example
  title: Support for `additionalProperties` declarations
  description: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#schema-object
  version: 1.0.0
servers:
  - url: https://httpbin.org
paths:
  '/post':
    post:
      summary: Should allow additionalProperties in JSON schema
      description: Should allow additionalProperties in JSON schema details
      operationId: post-post
      tags:
      - additional
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                'object with `additionalProperties: true`':
                  type: object
                  additionalProperties: true
                'object with `additionalProperties: false` and no other properties':
                  type: object
                  additionalProperties: false
                'object with `additionalProperties: { type: integer }`':
                  type: object
                  additionalProperties:
                    type: integer
                'object with `additionalProperties: { type: object, properties: ... }`':
                  type: object
                  additionalProperties:
                    type: object
                    properties:
                      code:
                        type: integer
                      text:
                        type: string
                'object with `additionalProperties: { type: object, properties: ... }` and custom title':
                  type: object
                  additionalProperties:
                    type: object
                    properties:
                      code:
                        type: integer
                      text:
                        type: string
                    title: This is a custom title
                'object with `additionalProperties: { type: array, items: { type: integer } }`':
                  type: object
                  additionalProperties:
                    type: array
                    items:
                      type: integer
                'object with `additionalProperties: $ref, simple`':
                  type: object
                  additionalProperties:
                    '$ref': '#/components/schemas/ref'
                'object with `additionalProperties: $ref, with $ref`':
                  type: object
                  additionalProperties:
                    '$ref': '#/components/schemas/ref-with-ref'
                object with `additionalPropeties` within an allOf:
                  description: Technically this is not valid to the spec. The `additionalProperties`
                    rejections should cancel out each others new field but we indicate
                    we want this to work by enabling [json-schema-merge-allof](https://npm.im/json-schema-merge-allof)'s
                    `ignoreAdditionalProperties` option
                  allOf:
                    - type: object
                      additionalProperties: false
                      properties:
                        primitiveProperty:
                          type: string
                    - type: object
                      additionalProperties: false
                      properties:
                        alt_primitiveProperty:
                          type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  'object with `additionalProperties: true`':
                    type: object
                    additionalProperties: true
                  'object with `additionalProperties: { type: integer }`':
                    type: object
                    additionalProperties:
                      type: integer
                  'object with `additionalProperties: { type: object, properties: ... }`':
                    type: object
                    additionalProperties:
                      type: object
                      properties:
                        code:
                          type: integer
                        text:
                          type: string
                  'object with `additionalProperties: { type: object, properties: ... }` and custom title':
                    type: object
                    additionalProperties:
                      type: object
                      properties:
                        code:
                          type: integer
                        text:
                          type: string
                      title: This is a custom title
                  'object with `additionalProperties: { type: array, items: { type: integer } }`':
                    type: object
                    additionalProperties:
                      type: array
                      items:
                        type: integer
                  'object with `additionalProperties: $ref, simple`':
                    type: object
                    additionalProperties:
                      '$ref': '#/components/schemas/ref'
                  'object with `additionalProperties: $ref, with $ref`':
                    type: object
                    additionalProperties:
                      '$ref': '#/components/schemas/ref-with-ref'
components:
  schemas:
    ref:
      example: 45
      type: integer
    ref-with-ref:
      example:
        code: 201
        text: OK
      description: Object ref-with-ref
      type: object
      properties:
        code:
          example: 201
          type: integer
        text:
          example: Arbitrary text
          type: string
        array:
          example:
            - 30
            - 31
            - 33
          type: array
          items:
            '$ref': '#/components/schemas/ref'
