openapi: 3.0.1
tags:
  - name: anything
info:
  contact:
    name: HttpBin
  description: API definition
  title: API definition with a circular $ref
  version: 1.0.0
servers:
  - url: https://httpbin.org
paths:
  '/anything':
    get:
      operationId: get-anything
      description: Get anything
      tags:
        - anything
      responses:
        '200':
          description: OK
        '404':
          description: Not found
          content:
            application/json:
              schema:
                '$ref': '#/components/schemas/ErrorMessage'
components:
  schemas:
    ErrorMessage:
      type: object
      additionalProperties: false
      properties:
        statusCode:
          type: integer
          format: int32
        error:
          type: string
          nullable: true
        inner:
          '$ref': '#/components/schemas/ErrorMessage'
        canBeRetried:
          type: string
          enum:
            - Unknown
            - 'Yes'
            - 'No'
        detailedErrorCode:
          type: integer
          format: int32
