openapi: 3.0.3
tags:
  - name: post
info:
  contact:
    name: Example
  title: Cookie parameters
  description: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#parameter-object
  version: 1.0.0
servers:
  - url: https://httpbin.org
paths:
  '/post':
    post:
      operationId: post-post
      description: post post
      tags:
        - post
      parameters:
        - in: cookie
          name: foo
          schema:
            type: string
        - in: cookie
          name: bar
          schema:
            type: string
      responses:
        '200':
          description: OK
