openapi: 3.0.3
tags:
  - name: multiple
  - name: single
info:
  contact: 
    name: Example
  title: Responses with multiple media types
  description: https://github.com/OAI/OpenAPI-Specification/blob/master/versions/3.0.3.md#responseObject
  version: 1.0.0
servers:
  - url: https://httpbin.org
paths:
  '/multiple-types-multiple-examples':
    post:
      operationId: post-multiple-types-multiple-examples
      tags:
        - multiple
      summary: Multiple types, multiple examples
      description: Multiple response types with multiple examples
      requestBody:
        description: Request body multiple-types-multiple-examples
        content:
          application/json:
            example: {
              'string (format: date-time)': '2024-03-09T13:00:00Z'
            }
            schema:
              type: object
              properties:
                'string (format: date)':
                  example: '2024-03-09'
                  type: string
                  format: date
                'string (format: date-time)':
                  example: '2024-03-09T13:00:00Z'
                  type: string
                  format: date-time
                'string (format: string)':
                  example: String
                  type: string
                  format: string
      responses:
        '200':
          description: OK
          content:
            text/plain:
              examples:
                response:
                  value: OK
            application/json:
              examples:
                cat:
                  summary: An example of a cat
                  value:
                    name: Fluffy
                    petType: Cat
                    color: White
                    gender: male
                    breed: Persian
                dog:
                  summary: An example of a dog with a cat's name
                  value:
                    name: Puma
                    petType: Dog
                    color: Black
                    gender: Female
                    breed: Mixed
        '400':
          description: Validation failed
          content:
            application/xml:
              examples:
                response:
                  value:
                    <?xml version="1.0" encoding="UTF-8"?><note><to>Tove</to><from>Jani</from><heading>Reminder</heading><body>Don't
                    forget me this weekend!</body></note>
  '/multiple-types-single-example':
    post:
      operationId: post-multiple-types-single-example
      description: Multiple response types with a single example
      summary: Multiple response types, single example
      tags:
        - single
      requestBody:
        description: Request body multiple-types-single-example
        content:
          application/json:
            example: {
              'string (format: date)': '2024-03-08'
            }
            schema:
              type: object
              properties:
                'string (format: date)':
                  example: '2024-03-08'
                  type: string
                  format: date
                'string (format: date-time)':
                  example: '2024-03-08T13:00:00Z'
                  type: string
                  format: date-time
                'string (format: string)':
                  example: String
                  type: string
                  format: string
      responses:
        '200':
          description: OK
          content:
            text/plain:
              examples:
                response:
                  value: OK
            application/json:
              examples:
                cat:
                  summary: An example of a cat
                  value:
                    name: Fluffy
                    petType: Cat
                    color: White
                    gender: male
                    breed: Persian
        '400':
          description: Validation failed
          content:
            application/xml:
              examples:
                response:
                  value:
                    <?xml version="1.0" encoding="UTF-8"?><note><to>Tove</to><from>Jani</from><heading>Reminder</heading><body>Don't
                    forget me this weekend!</body></note>
  '/single-type-multiple-examples':
    get:
      operationId: get-single-type-multiple-examples
      tags:
        - single
      description: Single media type with multiple examples
      summary: Single media type, multiple examples
      responses:
        '200':
          description: OK
          content:
            application/json:
              examples:
                cat:
                  summary: An example of a cat
                  value:
                    name: Fluffy
                    petType: Cat
                    color: White
                    gender: male
                    breed: Persian
                dog:
                  summary: An example of a dog with a cat's name
                  value:
                    name: Puma
                    petType: Dog
                    color: Black
                    gender: Female
                    breed: Mixed
        '400':
          description: Validation failed
          content:
            application/xml:
              examples:
                response:
                  value:
                    <?xml version="1.0" encoding="UTF-8"?><note><to>Tove</to><from>Jani</from><heading>Reminder</heading><body>Don't
                    forget me this weekend!</body></note>
  '/single-type-single-example':
    get:
      operationId: get-single-type-single-example
      summary: Single media type, single example
      description: Single media type with a single example
      tags:
        - single
      responses:
        '200':
          description: OK
          content:
            application/json:
              examples:
                cat:
                  summary: An example of a cat
                  value:
                    name: Fluffy
                    petType: Cat
                    color: White
                    gender: male
                    breed: Persian
        '400':
          description: Validation failed
          content:
            application/xml:
              examples:
                response:
                  value:
                    <?xml version="1.0" encoding="UTF-8"?><note><to>Tove</to><from>Jani</from><heading>Reminder</heading><body>Don't
                    forget me this weekend!</body></note>
